/**
 * server.js — cPanel Node.js startup file
 *
 * Set this file as the "Application startup file" in cPanel's
 * Node.js Selector. Requires `next build` to have been run first.
 */

process.env.NODE_ENV = "production";

// The standalone server generated by `next build` (output: 'standalone')
require("./.next/standalone/server.js");
